# Read the val dataset

In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/dontpatronizeme_pcl.tsv', sep='\t')

# Remove rows with NA labels 
df = df.dropna() 

# Add a bool_labels column for binary classification
df["bool_labels"] = df["label"] > 1   # is PCL if >1
val_labels = pd.read_csv('../data/dev_semeval_parids-labels.csv')["par_id"]  # extract the labels for val dataset 
df_val = df[df["par_id"].isin(val_labels)].reset_index()

# Read the prediction results: 
- baseline.txt (Roberta) 
- only_oversample.txt (Baseline Roberta + Oversample)
- roberta_ensemble.txt (Baseline Roberta + Oversample + Context)
- oversample_context_cr.txt (Baseline Roberta + Oversample + Context + Coreference resolution)
- bert_ensemble.txt (BERT + Oversample + Context)
- final.txt (Same as dev.txt, ensembles)

In [2]:
with open("baseline.txt", "r") as f: 
    y_pred_baseline = np.array([int(x) for x in f.read().split("\n")]) 

with open("only_oversample.txt", "r") as f: 
    y_pred_only_oversample = np.array([int(x) for x in f.read().split("\n")]) 

with open("roberta_ensemble.txt", "r") as f: 
    y_pred_roberta_ensemble = np.array([int(x) for x in f.read().split("\n")]) 

with open("oversample_context_cr.txt", "r") as f: 
    y_pred_oversample_context_cr = np.array([int(x) for x in f.read().split("\n")]) 

with open("bert_ensemble.txt", "r") as f: 
    y_pred_bert_ensemble = np.array([int(x) for x in f.read().split("\n")]) 

with open("final.txt", "r") as f: 
    y_pred_final = np.array([int(x) for x in f.read().split("\n")]) 

y_true = df_val["bool_labels"]

In [3]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

preds = [y_pred_baseline, y_pred_only_oversample, y_pred_roberta_ensemble, y_pred_oversample_context_cr, y_pred_bert_ensemble, y_pred_final]
for pred in preds: 
    print("="*50)
    
    print(f"Accuracy: {accuracy_score(y_true, pred):.3f}")
    print(f"Precision: {precision_score(y_true, pred):.3f}")
    print(f"Recall: {recall_score(y_true, pred):.3f}")
    print(f"F1: {f1_score(y_true, pred):.3f}")

==================================================
Accuracy: 0.920
Precision: 0.582
Recall: 0.573
F1: 0.577
==================================================
Accuracy: 0.917
Precision: 0.559
Recall: 0.618
F1: 0.587
==================================================
Accuracy: 0.915
Precision: 0.541
Recall: 0.724
F1: 0.619
==================================================
Accuracy: 0.913
Precision: 0.536
Recall: 0.598
F1: 0.565
==================================================
Accuracy: 0.918
Precision: 0.577
Recall: 0.528
F1: 0.551
==================================================
Accuracy: 0.920
Precision: 0.561
Recall: 0.719
F1: 0.630

# Examples of tp, tn, fp, fn for each class
Evaluated using the final model

In [7]:
pd.set_option("display.max_colwidth", None) 

keywords = ['homeless', 'disabled', 'poor-families', 'in-need', 'women', 'refugee', 'migrant', 'hopeless', 'immigrant', 'vulnerable']

# Extract examples of TP, TN, FP, FN, for each keyword
for keyword in keywords: 
    print("="*50)
    print(f"Keyword: {keyword}")
    print("="*50)
    tp = df_val[(df_val["keyword"] == keyword) & (y_true == 1) & (y_pred_final == 1)]
    tn = df_val[(df_val["keyword"] == keyword) & (y_true == 0) & (y_pred_final == 0)]
    fp = df_val[(df_val["keyword"] == keyword) & (y_true == 0) & (y_pred_final == 1)]
    fn = df_val[(df_val["keyword"] == keyword) & (y_true == 1) & (y_pred_final == 0)]

    display(tp[["text", "bool_labels"]].head()) 
    display(tn[["text", "bool_labels"]].head())
    display(fp[["text", "bool_labels"]].head()) 
    display(fn[["text", "bool_labels"]].head())

==================================================
Keyword: homeless
==================================================

,text,bool_labels
7,"It can not be right to allow homes to sit empty while many struggle to find somewhere to live , others having to sleep rough on pavements during Christmas , hoping against hope , for some charity to provide shelter . The number left homeless and destitute is alarming not necessarily at Christmas ?",True
26,"On the eve of the World Refugee Day , UNHCR received information about three new shipwrecks in the Mediterranean . It is feared that at least 130 people were dead or missing . Whatever the unpredictable Donald Trump may be doing or undoing , all our religions tell us that it is our sacred duty to give shelter to the homeless and that is what we need to do , discarding the trump cards from hell .",True
30,"Government support to bring the Housing First programme to Wellington will make a real difference for the homeless , says National 's Wellington Central candidate Nicola Willis .",True
39,"Behind the initiative are Danish national Lars Jorgensen and his American wife Monica , who came to the Philippines as backpacking tourists 27 years ago and were moved by the sight of Manila 's young and homeless .",True
45,"The drama 's compelling nature derived from a thorough knowledge of its cast , more numerous and improbable than any soap opera 's . The bite came from underlying tragedy : lost wives , lost jobs , pennilessness , homelessness and death . I have never laughed so much as in Soho in the Eighties .",True

,text,bool_labels
180,Clashes left 300 villagers homeless in Khagrachhari,False
181,"He regretted that in 2014 , Boko Haram killed 6,644 people and rendered more than one million homeless , making it the world 's deadliest militant group , according to Global Terrorism Index .",False
194,The Prime Minister said that construction of affordable housing initiative would not only provide shelter to the homeless but would generate huge economic activity by providing millions of jobs and boosting all linked industries of the housing sector .,False
215,He further alleged that it is unthinkable that the government of an independent country can make people homeless by killing them in police firing and resorting to attacks and torching .,False
223,"Loach remains just as passionate about social injustice as when his TV play "" Cathy Come Home "" shocked viewers 50 years ago with its depiction of a slide into homelessness .",False

,text,bool_labels
326,"As leaders , we will personally support victims but we ask the government to also help . We are going to clear all victims ' hospital bills and we want to ensure that those left homeless receive shelter .",False
356,His friends at the Chevron want people to know he was n't just a faceless homeless person . He was their friend and their family .,False
446,"Allman Town resident Sonya Wilson ( second left ) , and one of her daughters ( fourth left ) hand out boxed lunches to a group of homeless people on King Street , downtown Kingston , on Thursday .",False
500,"Black grew up in the neighbourhood around the church , where he would eat Franklin 's cooking at lavish meals she provided for the community and the homeless each Thanksgiving and Christmas . "" She made the best oxtail soup , with that cornbread , and it was to die for , "" he recalled . "" It would be so much food that you would n't know what to do . """,False
634,"6 years ago she lost her husband -- he died from heart disease , and since then Wood lives alone with her children and a dog . When she learnt about Michael and Cory 's terrible life problems , she realised she had to help . This woman has a big kind heart . There were 2 empty rooms in her house , so she invited the homeless to live there . Many people might consider her action as a madness but Mel says that since her husband 's death , she does n't fear anything .",False

,text,bool_labels
0,"His present "" chambers "" may be quite humble , but Shiyani has the tiny space very neatly organized and clean . Many people pass him by but do not manage to see him , because the space is partially hidden behind trees , which gives him a relative privacy . "" There are many homeless sleeping around the station , "" Captain Xoli Mbele , from the nearby Johannesburg Central Police station said .",True
12,"It 's calculated that over 204,000 days of purpose-built residential accommodation to otherwise potentially homeless elderly men and women have been delivered by this personally driven altruistic act alone .",True
20,"Bombarded by schizophrenia , addiction and homelessness , you might say that Eoghan O'Driscoll has been to hell and back . But he is finding a new balance through painting . Interview : Michael Lanigan",True
24,Mum living in homeless shelter has ' nowhere to bring boys on Christmas day ' <h> ' panicked ',True
49,"She remembers how hard being homeless hit her . She remembers , too , how she would try and act as mad as possible to intimidate people and stop them from coming close to her . She would turn as she walked and make loud noises so that people would leave her alone . How did she manage not to lose sight of her future while she was struggling for survival ? "" I handled my situation of being homeless pretty easily , "" she says with a bit of distance . "" I had football to focus on . I wanted to represent my country and I was n't going to let anything get in the way . """,True

==================================================
Keyword: disabled
==================================================

,text,bool_labels
3,"When some people feel causing problem for some others by breaking into their homes to steal is n't too good , they just result to begging . You now see people without deformities begging , when some people who are disabled work to feed their mouth . You then ask , what type of country is Nigeria ? Even a man who is not lettered would chorus the maxim that two wrongs do n't make a right . The country is n't working out ; and people want to survive anyhow too . They have to eat they will say .",True
33,"Haiti has legal protections for the disabled on paper , but the laws are poorly implemented . Disabled Haitians have few opportunities to work and too many youngsters with disabilities languish out of sight at home instead of going to school . Some impoverished parents abandon disabled kids outside state institutions or farm them out as domestic servants .",True
36,"Kyle really your a pig , lol youre also very ignorant do nt like over weight women , well have u looked in the mirror recently your FAT , YOU AND YOUR BOSS SHOULD BE SACKED never to return to radio , , how dare you say go for the disabled , your more disabled than the disabled olympians , they have a genuine heart , you do nt have one ,",True
47,"She added that her office has worked relentlessly with the present administration to translate policies into concrete actions for the women , children , the aged , orphans , the disabled , and other vulnerable members of the society . Hajiya Yuguda challenged Nigerians to believe in the immense capacity and capability of the women folk in nation building in order to bring about the much needed positive change the country is yearning for .",True
50,""" My daughter , who was a physiotherapist , who is now on the other side , realizes how difficult it is being a disabled person . She wishes to change the idea in people 's minds when they look at a disabled person -- their mind is fine , they may be disabled , but they 're normal people and they want to be treated that way . """,True

,text,bool_labels
166,"Last week , the rights office reported dozens of execution-style killings in villages near Mosul , including the shooting of a physically disabled girl who failed to keep up on a forced march .",False
177,"Sithole put South Africa on the map in disabled tennis , winning his first Grand Slam singles title in his category last month , following his win at the British Open in July .",False
191,""" However , disabled children need more attention in terms of curriculum adaptation , teaching methods , and availability of teaching and learning materials , assistive technology , assessment systems , as well as funds for more assistance in adapting the school environment , "" he stressed .",False
198,"Guided by the philosophy of "" Building Communities "" , Swire Properties established its Community Ambassador Programme in 2001 . The programme seeks to help the elderly , the disabled , children and disadvantaged families in the community .",False
217,"There will be two phases including a web based process where anyone can respond in writing in any language , to questions posed , and a process of face to face consultations with all stakeholders including women , disabled soldiers , the military , war widows and former child soldiers , amongst others , she added .",False

,text,bool_labels
176,Who has been responsible for the big advances in the treatment of the disabled ?,False
188,"A crew of disabled athletes will be tackling this weekend 's Chattanooga Waterfront Triathlon to show others with disabilities they , too , can participate in a healthy , active lifestyle .",False
247,The Jali family in Brown 's Farm was elated as the City of Cape Town donated wheelchairs to their disabled members .,False
633,The dream of a social protection plan whose role is to protect the elderly and the disabled from extreme forms of poverty through monthly stipends is quickly becoming a reality in Kenya .,False
899,""" I realised that it was not impossible to achieve anything in the world despite being disabled .",False

,text,bool_labels
1,"Krueger recently harnessed that creativity to self-publish a book featuring the poems , artwork , photography and short stories of 16 ill or disabled artists from around the world . She hopes the book , which contains some of her own work as well , will show how talented disabled people can be .",True
13,""" I and my daughter Monica are excited about providing a space for disabled people to be able to get together and earn fair prices for their work , "" Mr. Rogers said .",True
87,The law stipulated 21 rights of the disabled persons . The disabled persons must get the national identity cards and be listed in the voters roll . Even they will be able to contest in the polls .,True
95,"New Zealand has been getting more comfortable confronting difficult issues in primetime . Last year , Nigel Latta : The Hard Stuff 's exploration of suicide and teenagers ' online lives was a hit . Earlier this year another season of The Undateables , a British show about dating amongst the disabled and those with learning disabilities played at 8.45pm Mondays on TVNZ 2 . And despite the exploitative name , Embarassing Bodies has helped open eyes and minds to the reality of those whose physical form deviates from a societal conception of ' normal ' .",True
150,"Cheung said 20 disabled undergraduate students from seven universities will start their eight-week internship in government departments this month , receiving the same salaries as able-bodied colleagues of HK$9,600 a month .",True

==================================================
Keyword: poor-families
==================================================

,text,bool_labels
4,"We are alarmed to learn of your recently circulated proposals that would eviscerate the Lifeline program and leave many of the most vulnerable people in the country without access to affordable communications . As you are well aware , the Lifeline program provides a modest monthly subsidy of $9.25 to connect low-income Americans to phone and internet services . As broadband prices continue to soar , and affordability continues to suffer , adoption gaps remain . The Lifeline program has proven critical for poor families and people of color who are caught on the wrong side of the digital divide .",True
21,Valerie Siddiq : My heart goes out to all the deceased and the poor families . May God grant us tolerance for all race and religions .,True
23,BUSINESSMAN Norberto Quisumbing Jr . of the Norkis Group of Companies has a challenge for families who can spare some of what they have : why not adopt poor families and help them break the cycle of poverty ?,True
55,""" The worst thing was dealt to us , "" he said . "" But at least we 'll get closure . That 's a blessing , in some way ... but I think of those poor families who wo n't . """,True
58,"She said since Bangladeshs main export to the USA is apparel , this industry employs 4 million workers , of which 90 percent are girls from poor families . Their earnings have empowered them . Their contributions now provide better nutritional food , allow siblings to go to schools , and give them a respected voice at home . Their empowerment is also helping reduce poverty , control population growth and increase literacy .",True

,text,bool_labels
167,"Recommended changes to residential consumer tariff schemes will be designed to give more relief to poor families , especially those living in compound houses . <h> National Builders Corps",False
195,"There are some lesson Ethiopia can draw from Latin American countries that have used cash transfer schemes to support the poor . The government also needs to start focusing on redistribution of wealth rather than just rapid economic growth . Urban housing policies should ensure poor families have access to decent shelter . There should also be social security schemes to assist , especially households whose members are unemployed because of disability .",False
197,"MANILA , Philippines - The government will hold a second nationwide survey this summer to identify the poorest of the poor families .",False
211,The schools -- overseen by the King Edward VI charitable foundation in the city -- have been set a target to ensure at least one-in-five places are awarded to pupils from poor families . It coincides with a move to expand the schools to take an additional 130 children .,False
216,""" The results allow us to see there have been important changes over time in the composition of economically vulnerable families . . . many economically vulnerable families no longer fit the traditional profile of poor families , "" she said .",False

,text,bool_labels
169,Marcos said the government should help poor families that try every possible means to survive . With Joel Zurbano <h> More from this Category :,False
379,""" We want all poor families to earn enough and save enough . The rural savings banks were meant to encourage that . """,False
382,""" It is due to efforts of the government that land of a farmer can not be auctioned to recover loan . We provided fund for girls from poor families . If we count the list is very long , "" he said .",False
458,"She recalled being so proud of being part of a small group of students involved in "" The Goat Project "" where students raised money to help poor families in Africa .",False
617,"On the occasion , Major Fahad also distributed ration among the 40 poor families present at the medical camp . He said that army had been struggling to protect and serve the people of Swat and had stood by them in every troubled hour . People hoped that more such free medical camps would be arranged in the future .",False

,text,bool_labels
2,"10:41am - Parents of children who died must get compensation , free medicine must be provided to poor families across UP : Ram Gopal Yadav",True
44,t is remiss not to mention here that not all scavenging children come from poor families . Children hailing from affluent families use dumpsites as playgrounds .,True
53,Camfed would like to see this trend reversed . It would like to see more girls in school . Basic Education Statistics in Tanzania ( BEST 2010 ) show that only 18 percent of girls have completed secondary school education . This is why Camfed supports girls from poor families to obtain secondary education and its efforts have seen many go to university .,True
69,""" Some come from poor families and then you find swimming in millions and they lose focus , then they fizz out from football altogether , "" he said , making it clear that to have a Paul Pogba-esque success , one needs to work that much harder and not get influenced easily especially at this age and that too coming from Africa .",True
101,"So when journalists and observers tell us that , "" Toronto will never be the same again , "" they are not only wrong , but are extremely unhelpful . Of course Toronto will be just the same again . Not for the poor families of the deceased , not for those struggling with ghastly and perhaps life-changing injuries , but for most of the rest of us . It wo n't change , because it never does .",True

==================================================
Keyword: in-need
==================================================

,text,bool_labels
5,""" We share a global responsibility to respond to this crisis . We commend others who have acted in a compassionate and generous way , especially the Government of Bangladesh and host communities in the region who continue to provide safe refuge to their neighbours in need , "" he said .",True
6,"The former Chelsea star through his foundation gave out toys , bags and clothes to kids in need of a brighter holiday",True
14,"When contacted , Yadav said , "" There are two things that drive me to deliver my best . The sense of responsibility that I have as an officer of the Government of India . And , I get happy when I see smiles on the faces of people who are caught up in the complexities of bureaucracy . If the government is paying me for taking up responsibilities , then it becomes my duty to help those in need . """,True
17,He wants more done now to help those in need .,True
18,"He said : "" We need improved security for civilians and aid workers and access to all those in need , but we must also build a bigger humanitarian muscle to provide for the suffering millions .",True

,text,bool_labels
172,""" These lengthy , inefficient and burdensome processes result in more hindrance than assistance to SMEs that are more in need of government assistance than larger firms to enter international markets , "" the study highlighted .",False
192,"As reported by Sport24 , it 's widely expected that current South Africa rugby coach Allister Coetzee will see his contract terminated in the very new future . SARU would of course then be in need of a replacement , but even still , the muted appointment of Erasmus would raise eyebrows for a number of reasons . SA Rugby are believed to be currently working on a five-year contract to be offered to Erasmus upon the sacking of Coetzee .",False
203,"Bangladesh 's bowling could do better , however . Mehidy Hasan Miraz and Nazmul Islam will once again need to slow things down while Mustafizur Rahman and Rubel Hossain have to bowl well in the power play and slog overs . Taskin Ahmed may have to give away his place after being below par .",False
204,"Since the tournament increased its status to a tier 1 event and its prize money to $600,000 , each golfer would be in need of caddie this year .",False
205,"There are just on 20,000 members belonging to more than 350 VIEW clubs throughout Australia who raised more than $1million to support 1000 children in need .",False

,text,bool_labels
373,"Dacawi practically pioneered the concept of civic or community journalism in the city by writing on the plight of indigent patients , other people in need and worthwhile causes that moved people to respond .",False
388,""" Your personal leadership has been critical to addressing the plight of the Rohingya who fled to safety in your country . I thank you for all you have done to assist these men , women and children in need , "" he wrote in the message .",False
584,""" I always consider this job as a gift , being a nurse is a reward and task given by God to help those who are in need . Seeing your patient recover from an illness , watching their families smile when you give them care , and hearing the first cry of a newborn are just some of the things that make my work special . It might be a heavy work but it can lighten your heart , "" she expressed .",False
643,""" You also get to meet a lot of people "" enthuses Kanthi . Kanthi , has not only grasped the opportunity to meet a lot of people through dancing , but has also used the chance to reach out to those in need of help . The proceeds from ' Step by step ' will be in aid of the Society for Uplift and Rehabilitation of Leprosy Patients ( SUROL ) .",False
714,"Jesus begins his teaching in Matthew with the Sermon on the Mount . One group he blesses is those in need of comfort , Blessed are they who mourn , for they will be comforted ( Mt 5:4 ) .",False

,text,bool_labels
109,""" I have a lot of sympathy for folks who are in need in the city , "" Mr Edmonds-Waters said . "" This has become an extremely expensive city to live in . The divide between those who have and those who do n't is ridiculously ginormous . """,True

==================================================
Keyword: women
==================================================

,text,bool_labels
8,""" People do n't understand the hurt , people do n't understand the pain . I 've read about women with their children sleeping in cars , sleeping in hotel rooms and it 's criminal . If they 're lucky and they come across COPE Galway and the ladies in Osterley , then there 's hope . """,True
19,"She continued , "" I stepped away from hiding behind a fabricated version of myself . I no longer put actions behind my fears and insecurities . I made a choice to redirect my energy to be a catalyst for change . To create a channel for women to become the truest versions of themselves , along with me. """,True
65,""" We believe in the ability of young women to achieve great things , both for themselves and for Tanzania , "" he added .",True
85,"If in addition ' miracles ' can be orchestrated then the acceptance and reverence become total . In a country where statistics state that unemployment is about 25 per cent but we know it is more like 70 per cent , where the next meal will come from is unpredictable and on a daily basis time just passes by ; it is not far-fetched for women to become prayer warriors for their children , husbands and siblings and are made to blame whatever is happening not on policies of the government but on the machinations of the devil .",True
127,""" These poor ladies are definitely going through some traumatic issues right now , and I am asking that they come forward so that I help them ? together with women parliamentarians - to be able to heal .",True

,text,bool_labels
184,"So far , Roche has merely said Avastin helps women with advanced ovarian cancer live longer without their disease getting worse . Full details will be unveiled at the annual meeting of the American Society of Clinical Oncology in June .",False
185,"She said , on the commendations of the women wing , the PHF has barred women players of over thirty years of age from taking part in all national level hockey events to give ample opportunity to the young hockey talent to play hockey .",False
190,"New York Marathon title holder Geoffrey Kipsang Kamworor completed a hat-trick at the IAAF World Half Marathon Championships , after winning in Valencia -- Spain on Saturday evening as Ethiopian Netsanet Gudeta Kebede took the women 's title .",False
196,"She also witnessed the development of the economy of the districts affected by war while visiting an apparel factory in Ampara and seeing the booming in touristic infrastructures in Passekudah . In Batticaloa , she also visited several successful European Union-funded projects to support small businesses run by single women headed households , implemented by the French NGO ACTED . In Ampara , she participated to the opening of an Early Childhood Care and Development unit in the Zonal Education Office of Akairipattu , in the framework of a program financed by AFD , French Agency for Development and the French Organisation Solidarit ? La ? que and implemented throughout the Eastern Province with three local counterparts .",False
199,"MP Lisa Hanna has blamed the "" bloodsport "" nature of the Jamaican hustings for turning off most women from entering representational politics .",False

,text,bool_labels
252,"So , let the NPP government appointees look down upon the hardworking and selfless men and women at their own peril .",False
272,""" The government needs to come forward , and it needs to give resources to legal aid , so that those women and those families have their basic human rights and safety met , around representation and justice , the ability to navigate that Goliath of an office with a great deal of power , and to ensure they have the education and the advocacy that they need . "" <h> Child and Youth Advocate responds",False
384,Khushi said women 's participation in various sectors of the society should be increased and this will help change the attitude of the people towards them .,False
387,Her fate was to end up drowning herself in a bog because she would n't conform as women were expected to .,False
826,"Subsidised , affordable day care will allow more women to enter the workplace . This is something they want and it is only the cost of day care that is preventing them from doing so .",False

,text,bool_labels
35,"Mari ? tte Coetzee from Stofberg Family Vineyards ( whose Mia Chenin Blanc 2016 was the garagiste trophy winner at last year 's Michelangelo Awards and the recipient of four Platter 's stars for the Mari ? tte Chenin Blanc 2016 ) , says : "" We can be extremely proud of the current women winemakers in our industry , especially considering most of them are juggling a family along with the long working hours .",True
83,"We have done a great deal of work but the biggest thing we have done is to make the ministry a powerful tool for the protection of women ... Over the last four years , every time somebody comes up with a good idea or proposes an area in which women need help , we have adopted it immediately . We have been doing two things -- policymaking , which also pushes other ministries , and looking at individual cases of suffering . For me , both components are equally important .",True
97,"Maida noted that political issues should not twist women away from matters of development , the important thing is peace , and women must wake up , since they need economic revolution through peaceful means .",True
120,"Our country is in need of serious change . We can continue to celebrate women 's day , throw massive budgets at events , give out goody bags with a cute lipsticks and celebrate female achievers once a year . This is without taking away from exceptional women who truly are making inroads into their environments but we are not just a cute lipstick , or pair of shoes , we are not just pretty and soft and squishy . We are not just child bearers , and there for procreation . So , why are we as women , so accepting of the placating and mollification thrown at us and overlook the inequalities through acceptance . I am by no means militant , but often , as even in politics , focus is shifted on true issues by drawing public attention to other "" things "" in order for us to be distracted . By shifting our focus from relevant issues we forget why we were disgruntled and angry and nothing ever changes .",True
149,"KARACHI - On the eve of International Women 's Day , Pakistan People 's Party Chairman Bilawal Bhutto Zardari has announced that his party 's Women Wing will organise Karwan-e-Benazir rallies in all the provincial capitals and in Azad Jammu &amp; Kashmir , Gilgit-Baltistan and Fata to celebrate the day and PPP 's achievements for empowerment of women in the country .",True

==================================================
Keyword: refugee
==================================================

,text,bool_labels
28,"Pope Francis washed and kissed the feet of Muslim , Orthodox , Hindu and Catholic refugees in a moving ceremony during Holy Thursday Mass at a refugee centre on the outskirts of Rome . ( March 24 )",True
29,""" Stateless "" is the story of a forgotten group of Vietnamese refugees who spent over 16 years in the Philippines waiting for resettlement . Caught at the low tide of compassion fatigue by the international community , which led to the closure of refugee camps in Southeast Asia in the early 1990s , the refugees found themselves lost with no country to call home .",True
31,"Departing from his prepared remarks , Francis shared his experiences of the day earlier with thousands of people gathered for his blessing . He says among the 300 refugees he greeted Saturday on Lesbos was a Syrian widower with two children .",True
46,""" It 's the largest humanitarian tragedy of our time , "" Ninette Kelley , the UN high commissioner for refugees ' representative to Lebanon , told the Guardian earlier this month in an interview . "" We do not want the world to forget that people are suffering here . """,True
51,"One petition signer , the Reverend Everett Shattuck , 59 , a Church of the Brethren minister from Mill Creek , Indiana , said opening his home to refugees was part of the U.S. tradition of welcoming immigrants .",True

,text,bool_labels
165,Asylum seekers from Somalia were asked to report to Dadaab while those from other countries were asked to report to Kakuma refugee camp .,False
200,All four men lived at the same refugee centre in Salzburg .,False
222,"She further argued that , the then Mahama-led government granted the two detainees refugee status therefore , in accordance with the United Nations Convention on the status of refugees of 1951 and the 1967 Protocol of the Status of Refugees , as well as the provision of the Refugee Law 1992 , PNDC law 305D of Ghana , Ghana has the responsibility to protect them against return to a country where they have a reason to fear persecution .",False
230,"But HRW has called for "" unimpeded and unconditional access "" for **26;902;TOOLONG organizations like UNHCR and IOM to rescued migrants and refugees in order to assess their claims for refugee status .",False
232,"The situation has some parallels to Myanmar 's current Rohingya crisis : Hardliners from the majority Sinhala Buddhist population , including several monks , have engaged in a sustained propaganda campaign , using social media to spread anti-Muslim sentiments , proliferate hate speech and organize attacks . In fact , Buddhist monks organized and carried out an attack on 200 Rohingya refugees in Sri Lanka last year . But unlike in Myanmar , anti-Muslim violence is a relatively new phenomenon in Sri Lanka .",False

,text,bool_labels
343,""" The fact is that ruthless smugglers are preying on desperate migrants and refugees with no regard at all for human dignity , "" said Michele Sison , the US Deputy Ambassador to the UN .",False
415,"E-mail Address : * <h> A clinic called "" Hope "" helps a Syrian refugee boy cope with diabetes",False
931,"Perhaps one of Lahiri 's most lasting contributions was keeping written records of the conditions of the refugees , with vivid and heart wrenching descriptions of their plight .",False
969,"In Nyarugusu , Tanzania 's last major refugee camp , the government and United Nations are trying to end a rootless life for generations of people living -- and many born -- in exile .",False
971,"In an act of defiance against Hungarian authorities , which had suspended trains to Western Europe , between 1,200 and 2,000 refugees decided to walk from Keleti Station in Budapest to Vienna on Friday . Men , women , children -- even people on crutches -- marched from the late morning to evening , clutching bags filled with all the possessions they had .",False

,text,bool_labels
9,"He depicts demonstrations by refugees at the border post , their catastrophic living conditions and the desperate attempt of several hundred to cross a river a few kilometres from the camp to get into Macedonia on 14 March 2016 .",True
117,"IdeaRaya spokesman Maryam Ramli Lee in an interview with Malay Mail Online , September 10 , 2015 . For human rights , Idearaya is shining a spotlight on marginalised communities such as refugees and migrant workers , while its focus for philosophy this year would be on educating children to express themselves philosophically .",True
163,"Many refugees do n't want to be resettled anywhere , let alone in the US .",True

==================================================
Keyword: migrant
==================================================

,text,bool_labels
10,"18 December should serve as a time when we look with compassion at the fate of migrants , refugees and the internally displaced . It is especially a time when we must plan and increase resources for creative action .",True
15,"Her house now holds the memories and keepsakes of a migrant 's life well lived , selflessly offering her home and love to more than 100 British foster children and making history in the process -- along with her late husband -- - by being the first black couple in the Lambeth Council in South London to be allowed to foster white children .",True

,text,bool_labels
168,"Greek authorities say that 103 migrants picked up off a crippled yacht are being taken to port on the southern island of Crete . A coast guard statement says the vessel was located by a merchant ship east of Crete early today , after authorities received a distress call by phone . The yacht 's point of departure and destination were unknown . On Monday , the coast guard said it ...",False
170,"After 1896 , Chinese immigrants had to have a guarantor and the poll tax had to be paid in advance . The tax was waived after 1934 but not repealed until 1944 .",False
175,Latest News <h> NY mayor signs bills limiting deportation of Caribbean immigrants,False
178,"Beck said members of his group already have sent more than 1 million faxes to members of Congress since the start of the year . The group also posted a petition on its website opposing a proposal by the bipartisan group of senators known as the Gang of Eight to legalize undocumented immigrants "" in a time of budget-deficit crisis and high unemployment . """,False
179,"Illegal immigrants from Bangladesh speak to the media at the Immigration office in Dar es Salaam , yesterday shortly before they were deported . According Immigration official Edmund Novaita , the 20 Bangladeshi nationals have served a 6-month jail term in Mtwara and Dar es Salaam after they were found guilty of illegally entering the country last year . ( Photo : Khalfan Said )",False

,text,bool_labels
1044,"In Gill Hoffs latest book , she takes us on a fascinating voyage across the sea . In this vivid account of life aboard a 19th century emigrant ship -- with it diverse assemblage of life -- a searing tale of hopeful passengers emerges who find their fates are bound together by the utterly self-serving actions of their captain .",False
1110,"Riss says he wanted to depict the hypocrisy of Europeans ' reaction to the crisis as well as the "" disenchantment "" awaiting the migrants reaching the continent 's shores alive .",False
2023,""" I think you will see President Trump being willing to give legal status to some of the illegal immigrants who are not bad hombres if he can get better border security and more robust legal immigration , "" he said . "" I may be wrong but I think he can fix this . "" <h> Different places , different issues",False

,text,bool_labels
34,If only we had more stories that championed the brilliance of migrant workers perhaps we 'd be able to challenge the silence that permits them to be treated in such a disdainful way .,True
48,"The measures have kept the migrants living in limbo . The overwhelming majority have not been granted asylum and they lead a tenuous existence , often at the whims of the government .",True
54,Famously progressive San Francisco has among America 's most eco-friendly public policies and has declared itself a sanctuary to immigrants it considers persecuted by President Donald Trump 's administration .,True

==================================================
Keyword: hopeless
==================================================

,text,bool_labels
11,"Almost apocalyptic in its devastation , the wrath of one of the most powerful storms ever to hit the Atlantic is evidenced in the smashed ruins of Barbuda 's candy-coloured homes , the hopeless faces of residents who have lost everything they own , and the haunted eyes of their children .",True
37,""" They have made them to become hopeless and now , in "" going to God "" , they have ended up being deceived further and their situation is exploited and the society becomes even worse .",True
40,"TREVOR HAGAN/WINNIPEG FREE PRESS John Donovan , northern region director of the Addictions Foundation of Manitoba : ? Many of them are feeling pretty hopeless. ?",True
43,"American hegemony in industry is history , they simply allowed and even encouraged their prosperity to be exported to low -wage economies , resulting in local unemployed folk living in poverty , unable to pay the electricity bill and keeping themselves from depression and hopelessness by sniffing , snorting , smoking or injecting themselves with opiates .",True
57,"You know the type . She 's excelling in her field while tutoring underprivileged kids , running 5K fundraisers and adopting the most hopeless rescue dogs as pets -- and she 's not afraid to gloat about it .",True

,text,bool_labels
173,"Scott Dann- Sunderland have looked hopeless this season unfortunately and I think Crystal Palace are going to be able to take advantage of that this weekend . Dann has been a solid defender so far this campaign and seems to have a knack for scoring . So far this season , he has ten shots on goal which is an average of two per game . For a defender that 's a great return , and last week against Stoke he got rewarded for that with a goal . Along with his set piece threat , his points for a clean sheet this weekend can be a big time boost .",False
174,"The final days of this election campaign call for a certain kind of song . Hung over from arguments at the Thanksgiving dinner table , hopeless or hopeful , amid candidates ' last-gasp grandstanding , the government 's shameful fear-mongering , as polls flail and stamina flags -- what we need is some jump . Some get-up-'n-jump . Not just indignation but jubilation , a hatchback of electric guitars cheering for everything Monday gets to get up to .",False
182,"A book on depression that everyone should read , whether you suffer with mental illness or not . This award-winning ' modern classic ' is as much a celebration of being alive as a look at the dark side of living . And its core message is the most important of all - that nothing is ever hopeless . ( And a PS for any self-help super geeks out there , Haig 's follow-up ' Notes on a Nervous Planet ' is out in July ) .",False
186,""" I voted twice before , but now I do n't have that drive anymore . Right now I feel hopeless , "" said Blessed . "" The two major political parties have me feeling like an old man grasping for a little air , and no matter what I do , none of them can assist me by giving me a little air . They are hopeless . The country is doomed . """,False
189,Mancha Spokesperson Imran H Sarker said the scrapping of Nizami 's review plea against his death sentence brought to an end the ' hopeless ' situation created by the ' unnecessary delays ' in bringing to justice Bangladesh 's war criminals .,False

,text,bool_labels
254,""" So we do need to heal ourselves as an Aboriginal Torres Strait islander community , but also as a nation . "" <h> A life of hope , not hopelessness",False
538,"Bishop Moss told Bishop Golding that the leaders of the church are constantly faced with economic pressures , social degradation and an abysmal cloud of hopelessness and are being constantly challenged by corrupt systems . However , he said God wants them to make Him known among the confusion .",False
657,"The question that one should really ask is , is Siachen really worth all this fuss ? Why do our soldiers continue to stand eye-to-eye defending hopeless territory ? Many of them will actually never return to see their sons , wives , daughters or beloved . And the others who will be fortunate enough to return may be handicapped or suffer permanent mental damage .",False
733,""" It 's a hopeless situation , "" said the aid worker . "" You treat the children who are sick , and then they fall ill again because they are not getting the right food . """,False
746,"ATD wants to uplift the self-esteem of MNC residents , without making them feel hopeless or dependent .",False

,text,bool_labels
22,""" So many of us see the state of our home as some kind of reflection of our self-worth ( even though it 's not ! ) , and a mess can so easily make you feel like a failure . And for those who have mental illnesses , chronic illness , chronic pain , or disabilities , this can be even worse , because when you 're not physically able to do a whole-house clean , it can all seem a little hopeless . """,True
42,"The Global Gender Gap Report 2016 has ranked Pakistan 143 out of 144 countries . This really demonstrates the failure of feminists who are hopeless to break the historical shackles of bondage on women and establish favorable political , educational , economic , and health conditions .",True
76,We also know that they can benefit by receiving counseling from someone who can help them understand that their feelings are normal and that their situation is not hopeless ; someone who can help them put their situation in perspective and help them communicate with others who could provide support ; someone knowledgeable about resources they can access ; someone who can help them plan for their needs and the needs of their child by developing either a parenting plan or an adoption plan .,True
108,"Calling for an immediate political solution to resolve the crisis in Syria , Erdogan said : "" Turkey 's incursion into northern Syria in early September had led to establishing peace , balance and stability in a region taken over by hopelessness "" .",True
114,"The indigenous Palestinians see themselves abandoned by the powerful nations of the UN . In sheer hopelessness and a sense of dehumization they are , regrettably , now resorting to nihilistic activities trying to harm Israeli Jews and getting killed every day by the trigger happy Israelis - civilians and security forces alike . It is a sad development in a region that has cried for justice for too long -- almost 70 years - only to be ignored and severely punished for their noncompliance to the Zionist dream of Eretz Israel .",True

==================================================
Keyword: immigrant
==================================================

,text,bool_labels
16,"Sheepherding in America has always been an immigrant 's job , too dirty , too cold and too lonely for anyone with options .",True
63,Hollywood star Leo Di Caprio urges help for reuniting immigrant children with their families,True
122,"Canada has managed to accept immigrants , yet it keeps its citizens happy at the same time . In fact , the only populist revolution was pro-immigrant ! It can all be managed , in a humane way ; feeling the pain of those who have left their homes in search of peace or prosperity .",True
140,"Many celebrities wore blue ribbons to support the American Civil Liberties Union , which is seeking to shed light on the plight of young immigrants facing the potential of being deported .",True
1588,"THE jagged rocks , the stony beaches , the sweeping , heather covered hills ... the last views of the old country that faded from sight when a generation of immigrants set sail for the new world ( you can read that in Liam Neeson 's voice if you want ) .",True

,text,bool_labels
183,"The fact is that people from innumerable cultures and countries have always fought for freedom , equality and democracy . Democracy is not a patent of the West . If at all there is a threat to the Western civilization , it is not because of immigrants from the non-Western world but because of the growing inequality that is equally affecting people of Western origin . But that is altogether another debate .",False
187,"The 30-year-old unidentified victim , believed to be an Indonesian immigrant , was of moderate size , fair-skinned and clad in a pair of blue jeans .",False
226,"Marine police captured 21 South Asian illegal immigrants and a people smuggler in a sampan outside Hong Kong International Airport . The youngest would-be migrant was three years old , Apple Daily reported Thursday . The toddler 's 34-year-old father and ...",False
235,""" The US presidential campaign , putting undocumented immigrants and refugees in the spotlight , terrified them , "" Welcome Place counsellor Ghezae Hagos said . "" The election and inauguration of Mr Trump appears to be the final reason for those who came mostly last month . """,False
236,"Perhaps I am misinterpreting your comment but I moved to this country as an Indian immigrant ( barely able to speak English ) at the age of 7 and have lived in 4 cities and two countries within the UK Brexit or no Brexit , I refuse to entertain the idea that the UK is a racist country , certainly not one with anywhere close to 17m racists .",False

,text,bool_labels
954,Le r ? ve Canadien : French immigrants find Canada the land of opportunity,False

,text,bool_labels
52,"Nearly 15,000 West African teenagers leave their homes every year to play football in Europe . Few make good on their dreams . Some are lured by corrupt "" agents "" , smuggled across the searing Sahara and discarded in the streets of Europe , resigned to selling fake designer bags as undocumented immigrants . Others are nabbed by academies and feeder teams affiliated with European clubs and often dumped like bad stocks .",True
478,"But if the Supreme Court gives a favorable decision for the president , his immigration program would immediately take effect , changing the lives of eligible Filipino families and other immigrants .",True

==================================================
Keyword: vulnerable
==================================================

,text,bool_labels
27,"It is written in Ecclessiastes in the Bible that ' WOE TO ANY NATION WHERE A SLAVE BECOMES KING ' This typifies the situation in Nigeria since the inception of that country . I weep for my country when I visited home in 2009 and toured my alma mater- ABSU ... the infrastructural decay reduced me to tears . No matter how much OIL is sold in the world market the money will not change the corrupt/ sorry situation in Nigeria . The only thing that will change it is REVOLUTION . I weep for the children , pregnant women , the sick , infirms and the vulnerables who are trapped in this diabolical hole called Nigeria . My advice to Nigerians ... ' GOD WILL NOT DO FOR MAN WHAT MAN CAN DO FOR HIMSELF ' Wake and take your destinies in your hands stop calling on God for simple things you can do , learn from Egypt , Tunisia and Libya experience .",True
32,"This is a new education programme introduced in this district to ensure that each vulnerable girl and boy in this district is educated , protected , respected and valued and grows up to turn the tide of poverty .",True
64,"The Turkish Ambassador to Tanzania Ali Davutoglu has called on civil society groups and Tanzanians in general to join hands in helping orphans and vulnerable children , saying such responsibilities should not be left for the government alone .",True
82,""" We need to grow the economy in a way that we are helping those that are struggling -- families that are going to difficult times , and those that are in vulnerable situations , "" he said .",True
88,""" We shall remember him for the immense contribution he made to the many vulnerable sectors of humanity ? women ? children ? orphans the disabled and refugees . """,True

,text,bool_labels
171,"Monetary policy The IMF points out that further monetary tightening would head off second-round effects of currently high inflation , rein in credit expansion and protect against potential capital outflows from further US interest rate hikes . It suggests other measures to slow credit growth , including raising the reserve requirement and employing macro-prudential instruments , such as broader use of limits on loan-to-value ratios in vulnerable sectors and a credit limit or increasing risk weights in the housing sector .",False
201,"Last week , the Standard revealed Essex County Council would completely withdraw One Support , which provides social care to around 1,600 elderly and vulnerable residents with physical and mental health problems , from the Maldon district at the end of March . Vulnerable residents fear they will not be able to cope once their carers stop visiting them .",False
212,"New World Development ( NWD , 00017 . HK ) owns several commercial projects near the harbourfront area , making it vulnerable to criticisms that it will profit from its proposal to redevelop the Tsim Sha Tsui promenade , Apple Daily reported on Friday .",False
214,"The highest points total ND can now finish with is 103 , while Canterbury will have no fewer than 105 , a tally that still leaves them vulnerable to Auckland on the final day of the season .",False
218,The men were among a group convicted at London 's Southwark Crown Court of a 5.0 million pound ( $7.0 million ) scheme to steal public cash intended to be used to train vulnerable youngsters .,False

,text,bool_labels
626,""" Economic uncertainty can not be an excuse to slow down our development efforts , "" he said . "" It is a reason to speed them up . By investing in the MDGs , we invest in global economic growth . By focusing on the needs of the most vulnerable , we lay the foundation for a more sustainable and prosperous tomorrow . """,False
663,""" Protecting the disadvantaged members of our community is a cardinal role of any government and my administration in partnership with religious leaders will carry out fresh mapping of vulnerable members of our society and use the data to draw up a deliberate plan to support them , "" he said .",False
670,""" The UN Security Council must stand up and act to support vulnerable Palestinian people at the time when they need their protection . """,False
809,"It 's easy to dismiss the peace and love message as corny and pass ? , but Powers is convincing when she speaks of "" valuing people over things "" , and her beliefs are proven later when I learn of her considerable financial support of Taking it to the Streets , a charity helping vulnerable homeless youths , of whom there are many . ( This is depressing given the torrent of wealth pouring into the city from nearby Silicon Valley . If the Summer of Love set out to end stark inequality in its own community , it appears to have failed , despite the efforts of people like Powers . )",False
853,"In another development , Eiremiokhae was also bestowed with a Humanitarian Award by the Trinity International University of Ambassadors also in Georgia for his works of charity and care for widows and the vulnerable .",False

,text,bool_labels
41,"He said : "" I think we can consider introducing a negligible telecom surcharge to be entirely borne by the initiator of a call . In order to protect the poor and vulnerable amongst us , we could structure it to only take effect after the third minute of talk .",True
68,News this month that Anglican Care spent $4 million buying a Christchurch site as a hub for vulnerable youths is a fine example of that community-minded approach . In years to come there may be an interesting contrast between a beautifully restored cathedral that is empty much of the time and a youth hub and revamped City Mission that are constantly busy .,True
100,"Balu , an honest , hard-working labourer , who was injured by army shelling about 1993 leading to partial deafness , had latterly resettled in Tellipalai . While waiting to cross the KKS Rd. , he was killed by a navy vehicle with , as I learn , defective brakes , driven by a man without a heavy vehicle licence . When development fails the most vulnerable and poor , we have lost our way . It is well to remember Tagore in his essay on Nationalism : "" ... speed comes to its end , the engagement loses its meaning and the hungry heart clamours for food , till at last she comes to the lowly reaper reaping his harvest in the sun . """,True
143,"Emmanuelle Riva in "" Amour , "" as a woman in her 80s whose mind and body deteriorate after a series of strokes , is even frailer , more vulnerable , and quite defenseless . The first time we saw Riva , in "" Hiroshima Mon Amour , "" we were struck by her sensual , yet patrician face . Now the sensuality is gone , but the dignity of that countenance remains .",True
1753,"After a tragic event during his previous life as an FBI agent , Sawyer lost half a leg and developed an aversion to guns . So instead of the usual muscle-bound , wise-cracking , gun-toting cliche he 's often played , here he 's a vulnerable , disabled family man caught up in a twisted extortion plot .",True

In [77]:
# print(tp["keyword"].value_counts())
# print(tn["keyword"].value_counts())
print(fp["keyword"].value_counts())
print(fn["keyword"].value_counts())

keyword
poor-families    20
hopeless         17
in-need          17
vulnerable       13
homeless         12
disabled         11
refugee           9
women             9
migrant           3
immigrant         1
Name: count, dtype: int64
keyword
poor-families    14
women             8
hopeless          7
homeless          7
disabled          6
vulnerable        5
migrant           3
refugee           3
immigrant         2
in-need           1
Name: count, dtype: int64

# Metrics for each keyword for each model

In [73]:

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# F1, accuracy, precision, recall
for f in [f1_score, accuracy_score, precision_score, recall_score]: 
    data = [] 
    for keyword in keywords: 
        row = [keyword, df_val[df_val["keyword"] == keyword].shape[0], df_val[(df_val["keyword"] == keyword) & (df_val["bool_labels"] == True)].shape[0]]
        for pred in preds: 
            row.append(round(f(df_val[df_val["keyword"] == keyword]["bool_labels"], pred[df_val["keyword"] == keyword]), 3)) 
        data.append(row) 

    row = ["OVERALL", df_val.shape[0], df_val[df_val["bool_labels"] == True].shape[0]]
    for pred in preds: 
        row.append(round(f(df_val["bool_labels"], pred), 3)) 
    data.append(row) 

    data.sort(key = lambda x: x[1], reverse=True)

    df_f1 = pd.DataFrame(data)
    df_f1.columns = ["Keyword", "Count", "True Count", "Roberta Baseline", "Oversample", "Roberta ensemble (Oversample+Context)", "Oversample+Context+CR", "Bert ensemble", "Final"]
    display(df_f1)

,Keyword,Count,True Count,Roberta Baseline,Oversample,Roberta ensemble (Oversample+Context),Oversample+Context+CR,Bert ensemble,Final
0,OVERALL,2093,199,0.577,0.587,0.619,0.565,0.551,0.630
1,women,233,14,0.286,0.538,0.400,0.538,0.300,0.414
2,in-need,226,33,0.761,0.730,0.762,0.734,0.711,0.780
3,immigrant,218,7,0.600,0.364,0.769,0.333,0.600,0.769
4,hopeless,217,26,0.509,0.557,0.594,0.492,0.623,0.613
5,homeless,212,29,0.613,0.613,0.677,0.567,0.561,0.698
6,vulnerable,209,20,0.537,0.591,0.625,0.537,0.471,0.625
7,migrant,206,5,0.500,0.600,0.500,0.600,0.444,0.400
8,disabled,194,14,0.615,0.414,0.471,0.560,0.615,0.485
9,poor-families,190,38,0.560,0.528,0.588,0.560,0.492,0.585
10,refugee,188,13,0.462,0.667,0.606,0.429,0.261,0.625

,Keyword,Count,True Count,Roberta Baseline,Oversample,Roberta ensemble (Oversample+Context),Oversample+Context+CR,Bert ensemble,Final
0,OVERALL,2093,199,0.920,0.917,0.915,0.913,0.918,0.920
1,women,233,14,0.936,0.948,0.923,0.948,0.940,0.927
2,in-need,226,33,0.925,0.912,0.912,0.907,0.903,0.920
3,immigrant,218,7,0.982,0.968,0.986,0.963,0.982,0.986
4,hopeless,217,26,0.876,0.876,0.880,0.848,0.894,0.889
5,homeless,212,29,0.887,0.887,0.906,0.877,0.882,0.910
6,vulnerable,209,20,0.909,0.914,0.914,0.909,0.914,0.914
7,migrant,206,5,0.981,0.981,0.971,0.981,0.976,0.971
8,disabled,194,14,0.948,0.912,0.907,0.943,0.948,0.912
9,poor-families,190,38,0.826,0.821,0.816,0.826,0.826,0.821
10,refugee,188,13,0.926,0.947,0.931,0.915,0.910,0.936

,Keyword,Count,True Count,Roberta Baseline,Oversample,Roberta ensemble (Oversample+Context),Oversample+Context+CR,Bert ensemble,Final
0,OVERALL,2093,199,0.582,0.559,0.541,0.536,0.577,0.561
1,women,233,14,0.429,0.583,0.375,0.583,0.500,0.400
2,in-need,226,33,0.711,0.659,0.627,0.630,0.628,0.653
3,immigrant,218,7,1.000,0.500,0.833,0.400,1.000,0.833
4,hopeless,217,26,0.483,0.486,0.500,0.410,0.543,0.528
5,homeless,212,29,0.576,0.576,0.636,0.548,0.571,0.647
6,vulnerable,209,20,0.524,0.542,0.536,0.524,0.571,0.536
7,migrant,206,5,0.667,0.600,0.429,0.600,0.500,0.400
8,disabled,194,14,0.667,0.400,0.400,0.636,0.667,0.421
9,poor-families,190,38,0.568,0.559,0.532,0.568,0.593,0.545
10,refugee,188,13,0.462,0.588,0.500,0.400,0.300,0.526

,Keyword,Count,True Count,Roberta Baseline,Oversample,Roberta ensemble (Oversample+Context),Oversample+Context+CR,Bert ensemble,Final
0,OVERALL,2093,199,0.573,0.618,0.724,0.598,0.528,0.719
1,women,233,14,0.214,0.500,0.429,0.500,0.214,0.429
2,in-need,226,33,0.818,0.818,0.970,0.879,0.818,0.970
3,immigrant,218,7,0.429,0.286,0.714,0.286,0.429,0.714
4,hopeless,217,26,0.538,0.654,0.731,0.615,0.731,0.731
5,homeless,212,29,0.655,0.655,0.724,0.586,0.552,0.759
6,vulnerable,209,20,0.550,0.650,0.750,0.550,0.400,0.750
7,migrant,206,5,0.400,0.600,0.600,0.600,0.400,0.400
8,disabled,194,14,0.571,0.429,0.571,0.500,0.571,0.571
9,poor-families,190,38,0.553,0.500,0.658,0.553,0.421,0.632
10,refugee,188,13,0.462,0.769,0.769,0.462,0.231,0.769

# Comparison with the baseline model

In [30]:
# Examples correctly classified for both models 
cc = df_val[(y_true == y_pred_final) & (y_true == y_pred_baseline)]
cw = df_val[(y_true == y_pred_final) & (y_true != y_pred_baseline)]
wc = df_val[(y_true != y_pred_final) & (y_true == y_pred_baseline)]
ww = df_val[(y_true != y_pred_final) & (y_true != y_pred_baseline)]

display(cc[["text", "bool_labels"]].sample(frac=1).head()) 
display(cw[["text", "bool_labels"]].sample(frac=1).head()) 
display(wc[["text", "bool_labels"]].sample(frac=1).head()) 
display(ww[["text", "bool_labels"]].sample(frac=1).head())

,text,bool_labels
904,"Barring a disabled list stint for veteran Brett Gardner , who is nursing a sore knee , Frazier likely will be up for only a couple of days before heading back to the minor leagues . He has been in four major league games this year and has played 42 in the minors .",False
1811,"Movements require a mobilising vision , commitment , organisation , struggle , feedback , and participatory decision-making . Otherwise , any progress will be sporadic , temporary and insufficient to overcome the political inertia . The hopeless response to constructive proposals will remain : who is listening ?",False
1644,Race Relations Commissioner Dame Susan Devoy is in Geneva and has asked a United Nations committee to urge the New Zealand government to initiate an inquiry into the physical and sexual abuse of children and disabled people held in state institutions . More&gt;&gt;,False
427,""" Our findings show that the large space requirements for the cheetah , coupled with the complex range of threats faced by the species in the wild mean that it is likely to be much more vulnerable to extinction than was previously thought , "" Durant said .",False
2008,""" The study finds that the Clean Power Plan will inflict severe and disproportionate economic burdens on poor families , especially minorities , "" said Alford in his prepared statement . "" The EPA 's proposed regulation for GHG greenhouse gas emissions from existing power plants is a slap in the face to poor and minority families .",False

,text,bool_labels
1460,TurkIt 's heartening to see that measures are being taken in Khyber Pakhtunkhwa ( KP ) to empower women and give them work opportunities . You ! takes a look ...,True
715,"The vast majority of girls and women caught in the exploitative global sex trade are not victims of kidnapping , like the Nigerian 276 abducted by Boko Haram , but rather of poverty . Human traffickers prey on poor families who do n't have access to education and are n't aware of their basic rights . Mired in grinding poverty , parents desperately take out loans on conditions they do n't understand , pledging their children on their debts .",True
471,Rulers of Nato states that are enthusiastic about propping up this strategic alliance financially seem to have no regard for the suffering of their people . Rising unemployment rates and falling living standards have spawned far-right and fascist groups that are attacking immigrants and pushing European societies towards anarchy .,False
1861,"BRITAIN 'S protracted campaign of budget cutting , started in 2010 by a government led by the Conservative Party , has delivered a monumental shift in British life . A wave of austerity has yielded a country that has grown accustomed to living with less , even as many measures of social well-being - crime rates , opioid addiction , infant mortality , childhood poverty and homelessness - point to a deteriorating quality of life .",False
1541,"Columns <h> Poor , pregnant and homeless",False

,text,bool_labels
1006,""" If government makes education free at all levels , it will help many of us from poor families . I am ready to return to school if I see someone who can train me . I am not happy that my madam 's children go to school and I only wash clothes , sell anything they give to me and do all the work in the house . """,False
1700,"Artist Proshanta Karmakar Buddha has created his own style of art that is both modern and unique . He longs for a world devoid of chaos , brutality and hopelessness . He anticipates a peaceful utopia where human empathy and cooperation transcend national boundaries . It may be a ' fool 's dream ' but a world without hope is not a world worth living in . The spirit of that hope echoes through his works . Till date , Buddha has put up 29 solo exhibitions and participated in at least 96 national and international group exhibitions .",False
2023,""" I think you will see President Trump being willing to give legal status to some of the illegal immigrants who are not bad hombres if he can get better border security and more robust legal immigration , "" he said . "" I may be wrong but I think he can fix this . "" <h> Different places , different issues",False
633,The dream of a social protection plan whose role is to protect the elderly and the disabled from extreme forms of poverty through monthly stipends is quickly becoming a reality in Kenya .,False
500,"Black grew up in the neighbourhood around the church , where he would eat Franklin 's cooking at lavish meals she provided for the community and the homeless each Thanksgiving and Christmas . "" She made the best oxtail soup , with that cornbread , and it was to die for , "" he recalled . "" It would be so much food that you would n't know what to do . """,False

,text,bool_labels
1096,"A happy day it was indeed when a 31 homeless street dogs found their forever homes in the loving arms of the kind children and adults who visited Embark 's ' Adopt A Dog Day ' at Lyceum International School , Nugegoda on the 15th of September . Students from grades 1 to 8 were invited to attend along with their families and friends . The organizers were delighted by the fact that all the puppies and adult dogs who had been put up for adoption found good homes and new families in record time . In fact , Embark ran out of dogs as the demand was so high , but this was just the first adoption day of many more to come at the Lyceum Schools , so everyone who missed out can find their forever friends at future adoption days .",False
1920,""" This definitive outcome is a testament to the foresight of those who launched the programme , believing that elimination was possible in one of the world 's most endemic countries . In human terms , these children will never have to worry about being disabled by lymphatic filariasis . """,False
446,"Allman Town resident Sonya Wilson ( second left ) , and one of her daughters ( fourth left ) hand out boxed lunches to a group of homeless people on King Street , downtown Kingston , on Thursday .",False
1,"Krueger recently harnessed that creativity to self-publish a book featuring the poems , artwork , photography and short stories of 16 ill or disabled artists from around the world . She hopes the book , which contains some of her own work as well , will show how talented disabled people can be .",True
9,"He depicts demonstrations by refugees at the border post , their catastrophic living conditions and the desperate attempt of several hundred to cross a river a few kilometres from the camp to get into Macedonia on 14 March 2016 .",True

In [31]:
# For examples that were previously wrong but now correct, inspect its keyword distribution 
cw["keyword"].value_counts()

keyword
homeless         8
hopeless         8
poor-families    7
vulnerable       6
refugee          5
in-need          5
immigrant        3
women            3
disabled         2
migrant          1
Name: count, dtype: int64

# Effect of oversample model
Comparing oversample only to baseline

In [36]:
# Sentences where only oversample performs better than baseline
cw = df_val[(y_true == y_pred_only_oversample) & (y_true != y_pred_baseline)]
display(cw[["keyword", "text", "bool_labels"]].sample(frac=1).head()) 

# Keyword distribution
cw["keyword"].value_counts()

,keyword,text,bool_labels
1897,hopeless,"Rather sad . Good set of pictures that tells a tale of survival , subsistence living , and hopeless nature of life in the tribal societies . Exploiting an unexpected geo-political bonanza is a temporary relief that is not sustainable . Education and economic development seem miles away .",True
715,poor-families,"The vast majority of girls and women caught in the exploitative global sex trade are not victims of kidnapping , like the Nigerian 276 abducted by Boko Haram , but rather of poverty . Human traffickers prey on poor families who do n't have access to education and are n't aware of their basic rights . Mired in grinding poverty , parents desperately take out loans on conditions they do n't understand , pledging their children on their debts .",True
2071,poor-families,"Desertification which affects Yunusari , Yusufari , Karasuwa , Machina , Geidam and Bursari local government areas is increasingly diminishing the space for agricultural activities and livestock development . For many years , Yobe state has been screaming and asking for help to deal with desertification because it is depriving many poor families of their means of livelihood and even shelter . One needs to just visit Tulo-Tulo in Yusufari Local Government Area to have a picture of the disaster that is making life more difficult every day for thousands of families .",False
153,refugee,"In Dublin , the Church of Ireland Archbishop Dr Michael Jackson reflected on the year drawing to a close and recalled the "" horrific conflagration at the halting site in Carrickmines "" and the death of Garda Tony Golden in Omeath , as well as the "" refugees fleeing from Syria "" and other parts of the Middle East and the "" forgotten peoples of Africa "" .",True
668,poor-families,"If the situation is worsening in the cities , it is likely that in rural and remote regions children are even more at risk , particularly in Balochistan and Sindh , where poverty is at its highest . No data is available on rural areas , but many families face a daily struggle to feed everyone and extra children can be seen as unaffordable . Though many Pakistani women would like to have access to family planning , the use of birth control methods is still very low for cultural reasons and abortion is illegal . One gynaecologist told IRIN "" the mothers themselves wish to save the children but they also see the economic struggle of their families in a time of growing inflation "" . It says something about the sheer desperation of poor families in Pakistan , that murdering infants is seen as the only option open to them .",False

keyword
homeless         7
poor-families    7
refugee          6
hopeless         6
women            5
vulnerable       4
in-need          3
migrant          2
disabled         1
Name: count, dtype: int64

# Effect of adding context
Compare oversample+context to oversample only

In [37]:
# Sentences where only oversample performs better than baseline
cw = df_val[(y_true == y_pred_roberta_ensemble) & (y_true != y_pred_only_oversample)]
display(cw[["keyword", "text", "bool_labels"]].sample(frac=1).head()) 

# Keyword distribution
cw["keyword"].value_counts()

,keyword,text,bool_labels
1227,homeless,"More than 200 people , young and old , were being fed at a soup kitchen . Many were homeless and all of them had an urgent need for some food to try and ward off the effects of the bitter weather .",False
1580,homeless,""" He was not a bum or a homeless guy , "" added Sisson .",False
386,poor-families,"I am shocked , disgusted and dismayed at yet another police incident that is being mishandled . How many poor families have had their loved ones senselessly perish at the hands of highly paid , supposedly "" professional "" police officers and have had to fight against an unjust system that allows these officers to literally get away with murder unpunished. ?",True
116,poor-families,Real poverty of Britain : Shocking images of UK in the Sixties where poor really meant poor <h> THESE hard-hitting photographs offer a glimpse into the harrowing day-to-day for poor families living in Britain during the Sixties .,True
1036,poor-families,""" We have not been paid for the last two months , this money has assisted many poor families and we would like the governor not to abolish the program completely as it will affect many households , "" she told Sunday nation .",False

keyword
homeless         9
in-need          9
poor-families    8
disabled         6
vulnerable       5
hopeless         5
immigrant        4
refugee          2
women            2
migrant          1
Name: count, dtype: int64

# Effect of CR
Compare oversample+context+CR to oversample+context

In [44]:
# Sentences where the CR fails
wc = df_val[(y_true != y_pred_oversample_context_cr) & (y_true == y_pred_roberta_ensemble)]
display(wc[["keyword", "text", "bool_labels"]].head()) 


print(wc["text"].tolist())

,keyword,text,bool_labels
8,women,""" People do n't understand the hurt , people do n't understand the pain . I 've read about women with their children sleeping in cars , sleeping in hotel rooms and it 's criminal . If they 're lucky and they come across COPE Galway and the ladies in Osterley , then there 's hope . """,True
16,immigrant,"Sheepherding in America has always been an immigrant 's job , too dirty , too cold and too lonely for anyone with options .",True
18,in-need,"He said : "" We need improved security for civilians and aid workers and access to all those in need , but we must also build a bigger humanitarian muscle to provide for the suffering millions .",True
19,women,"She continued , "" I stepped away from hiding behind a fabricated version of myself . I no longer put actions behind my fears and insecurities . I made a choice to redirect my energy to be a catalyst for change . To create a channel for women to become the truest versions of themselves , along with me. """,True
33,disabled,"Haiti has legal protections for the disabled on paper , but the laws are poorly implemented . Disabled Haitians have few opportunities to work and too many youngsters with disabilities languish out of sight at home instead of going to school . Some impoverished parents abandon disabled kids outside state institutions or farm them out as domestic servants .",True

['" People do n\'t understand the hurt , people do n\'t understand the pain . I \'ve read about women with their children sleeping in cars , sleeping in hotel rooms and it \'s criminal . If they \'re lucky and they come across COPE Galway and the ladies in Osterley , then there \'s hope . "', "Sheepherding in America has always been an immigrant 's job , too dirty , too cold and too lonely for anyone with options .", 'He said : " We need improved security for civilians and aid workers and access to all those in need , but we must also build a bigger humanitarian muscle to provide for the suffering millions .', 'She continued , " I stepped away from hiding behind a fabricated version of myself . I no longer put actions behind my fears and insecurities . I made a choice to redirect my energy to be a catalyst for change . To create a channel for women to become the truest versions of themselves , along with me. "', 'Haiti has legal protections for the disabled on paper , but the laws are poorly implemented . Disabled Haitians have few opportunities to work and too many youngsters with disabilities languish out of sight at home instead of going to school . Some impoverished parents abandon disabled kids outside state institutions or farm them out as domestic servants .', '" They have made them to become hopeless and now , in " going to God " , they have ended up being deceived further and their situation is exploited and the society becomes even worse .', "Behind the initiative are Danish national Lars Jorgensen and his American wife Monica , who came to the Philippines as backpacking tourists 27 years ago and were moved by the sight of Manila 's young and homeless .", "The drama 's compelling nature derived from a thorough knowledge of its cast , more numerous and improbable than any soap opera 's . The bite came from underlying tragedy : lost wives , lost jobs , pennilessness , homelessness and death . I have never laughed so much as in Soho in the Eighties .", '" It \'s the largest humanitarian tragedy of our time , " Ninette Kelley , the UN high commissioner for refugees \' representative to Lebanon , told the Guardian earlier this month in an interview . " We do not want the world to forget that people are suffering here . "', 'The measures have kept the migrants living in limbo . The overwhelming majority have not been granted asylum and they lead a tenuous existence , often at the whims of the government .', 'One petition signer , the Reverend Everett Shattuck , 59 , a Church of the Brethren minister from Mill Creek , Indiana , said opening his home to refugees was part of the U.S. tradition of welcoming immigrants .', 'Over the past five years , the company has donated approximately 60,000 pounds of fresh produce for weekly outreach programs and via larger holiday events and Veteran ? s programs that have impacted tens of thousands of New Yorkers in need . Through Easter Seals of New York , Bloom Fresh delivers fresh fruits and vegetables each week to the Bronx Child Development Center to not only provide more healthy nutrients to children during lunch , but also for the children to take home to their families .', 'In a statement , the UNHCR said it is " alarmed and concerned " by Tuesday \'s incident and urged the " public and all those concerned with refugees to continue extending protection and to show empathy for civilians fleeing persecution and violence . "', 'President Muhammadu Buhari is on a divine mission to rescue the Nigeria from the brink of collapse and hopelessness , Speaker of the House of Representatives , Rt . Hon. Yakubu Dogara has said .', 'He said that he also stopped in Maiduguri , Nigeria , where he met with people who were torched out of their homes 11 months ago . " These are the stories we carry with us , " he underlined . " The World Humanitarian Summit , is a once in a generation opportunity to set in motion an ambitious and far reaching agenda to change the way that we alleviate , and most importantly that we prevent , the suffering of the world \'s most vulnerable people . "', '" We know Uber partners with an extensive network of drivers , and Plunket nurses support some of our most vulnerable families . Working together , we can make it simple for people to help out and make a difference , " Jarvie says .', "KOLKATA : Sourav Kaibartya , a fisherman 's son who scored 94.2% in his higher secondary examination this year got entry into NIT Durgapur for engineering course . The boy was at a loss as to who will fund his education . That is when a corporate house came into his rescue . Thirty-seven students like him from West Bengal meritorious but from poor families will now get to continue their studies with an initiative from Magma Fincorp Ltd .", 'Real poverty of Britain : Shocking images of UK in the Sixties where poor really meant poor <h> THESE hard-hitting photographs offer a glimpse into the harrowing day-to-day for poor families living in Britain during the Sixties .', 'ICCCAD remains a strong advocate of local initiatives and supports the concept of Community Based Adaptation ( CBA ) . Solutions developed at the local level have the best chance of being successful since it is the poorest living in areas prone to storms , floods , and droughts who are most vulnerable and best understand what needs to be done . This approach seeks to give these communities a voice since it is powerlessness as much as location that makes these communities vulnerable to climate change .', 'After the satisfying evening , Manny Osme ? a left us pondering on his quote , " Money is pressure until it is used to help people in need . "', 'That is the big picture , the one conveyed in official reports and government documents . But for the people who live on the ground in the province , it does not begin to portray the hopelessness , the everyday obstacles , the decay .', '" We are taking a community that is fairly vulnerable and bringing them to a level where they are empowered . " <h> VICTORIA KIOKO', 'Many celebrities wore blue ribbons to support the American Civil Liberties Union , which is seeking to shed light on the plight of young immigrants facing the potential of being deported .', 'There were also many larger events which took place , including a 24-hour long period of Eucharistic adoration and a prayer vigil . Additionally , " jubilees " were held which centered on , among others , the sick and disabled , catechists , teenagers , deacons , priests , religious , volunteers of mercy , and most recently , the poor and homeless .', 'In Dublin , the Church of Ireland Archbishop Dr Michael Jackson reflected on the year drawing to a close and recalled the " horrific conflagration at the halting site in Carrickmines " and the death of Garda Tony Golden in Omeath , as well as the " refugees fleeing from Syria " and other parts of the Middle East and the " forgotten peoples of Africa " .', 'There are just on 20,000 members belonging to more than 350 VIEW clubs throughout Australia who raised more than $1million to support 1000 children in need .', '" This incident will not tear us down but rather strengthen us as an organization . We will continue our mission of helping Veterans in need . It is through your generous donations and the volunteers in Chapter 84 that we have been able to provide transportation service for Veterans to their appointments at VA facilities and to build wheel chair ramps at no cost to the Veteran . There is scarcely a family in Alexander County that has not witnessed Chapter 84 \'s Honor Guard perform Military Rites at a loved ones funeral . Last year , Chapter 84 voted to support \' Dental Care for Veterans , \' a program that is getting underway by the DAV Department of North Carolina . Through this program , Veterans will be able to receive primary dental care at no charge .', "Mary Kay is one of the world 's largest direct selling companies with more than $3 billion in annual wholesale sales worldwide . Mary Kay was founded in 1963 by Mary Kay Ash with the goal of helping women achieve personal growth and financial success . Mary Kay remains committed to enriching women 's lives , and today more than 2.4 million people of all backgrounds are enjoying the advantages of being Mary Kay Independent Beauty Consultants . Mary Kay 's high-quality skin care and color cosmetic products are sold in more than 35 countries around the world . To learn more about Mary Kay , visit www.marykay.co.in", 'On Oct. 1 , at the Working America blog , a community affiliate of the AFL-CIO , New Hampshire writer Susan Bruce attempted to make sense of the outrage : " The lack of compassion is troubling but the level of anger is even more disconcerting . I suspect that the anger some people have for the homeless is fueled by their own fears that they are only a paycheck or two away from being homeless themselves . "', 'I am shocked , disgusted and dismayed at yet another police incident that is being mishandled . How many poor families have had their loved ones senselessly perish at the hands of highly paid , supposedly " professional " police officers and have had to fight against an unjust system that allows these officers to literally get away with murder unpunished. ?', "I am a Jaffna Tamil residing in the USA and I see the Sri Lankan professionals over here , both the Tamils and Sinhalese , holding top positions in Research , Universities HighTech industries , Law , and Finance.But then looking at the sterile Arab countries all we see are Sri Lankan women working as maids and servents to the rags to riches Arabs.A self respecting society would n't allow its women to be transported as maids to foreign land .", 'My sister and I were just talking about this yesterday . She was telling me how she had to chastise her assistant at work for using young kids as house help . She told her these are kids like her kids these children are serving but unfortunately that they are from poor families', '@Good Governance Forum : The worst part is that Govt does not seem serious in tackling the issue . Both provicial and Federal governments have been passing the blame on each other which is indicative of their reluctance to resolve the problem . Where should we go and to whom should we raise our voice . Karachiites are going through a helpless and hopeless situation.Recommend', 'The UN has failed to settle the Kashmir and Palestine disputes . Atrocities committed by India and Israel in these regions are gaining momentum . Palestinian and Kashmiris are living in fear and hopelessness . The current situation displays the dismal picture of abuse of power . The silence of the international community is incomprehensible . These are Muslim-majority areas and it seems that the world has no interest in the problems faced by Muslims .', "The vast majority of girls and women caught in the exploitative global sex trade are not victims of kidnapping , like the Nigerian 276 abducted by Boko Haram , but rather of poverty . Human traffickers prey on poor families who do n't have access to education and are n't aware of their basic rights . Mired in grinding poverty , parents desperately take out loans on conditions they do n't understand , pledging their children on their debts .", 'Feeling hopeless', 'These young girls are forced to drop out of school and become wives . Their dreams are completely destroyed and they become vulnerable to sexual and gender based violence , HIV and STI infection , Pregnancy related complications just to mention a few .', 'A child shows off his latest drawing as part of a class run by NGO Najda Now . The classes allow refugee children the chance to depict their dreams and fears through pictures , Dec. 4 , 2015 . ( J. Owens/VOA )', 'SL is forever stuck in hopelessness , till this generation of politicians are gone ...', 'But he said when the company sent him his refund , they \'re going to give all of the money to a group in Columbus that helps the homeless . " We \'re just going to donate it directly to that group and let them help other homeless people , because that \'s what was intended to happen , " he said .', "While some said they were just out to hang out with their friends of like persuasion , this was no social gathering for others ; it was a place of work . For some of these male prostitutes , the ' clients ' they picked up on this corner were their only means of survival , and the streets , in some cases , a home for the homeless among them .", 'Thus , the constitution to be , must contain no priestly doctrines , which brainwash public in to pessimism , fatalism and listlessness . In modern world , the king has become the politician , yet , his extant status continues , virtually , to be same , with no subjection to change . The constitutional contents must contain a foundation to battle with priestly doctrines , which produce rulers of despotism and which seed innocent people in the soil of sub-normality , racial hatred , religious antagonism and make them barren and hopeless . Constitution is not only a powering document , but also an educating instrument .', 'More than 200 people , young and old , were being fed at a soup kitchen . Many were homeless and all of them had an urgent need for some food to try and ward off the effects of the bitter weather .', "By contrast , the ' Asian Tigers ' devoted between 65 percent and 80 percent of their government education spending towards primary education . For example , South Korea decided early on that the government 's scarce resources must be focused on delivering the best primary education possible while the private sector was encouraged to invest in secondary and tertiary education . As a result , parents from poor families found their children to be so well prepared after primary school -- for free -- that they made every effort to pay for their education through private-sector secondary schooling , with a little help from government programmes where absolutely necessary . So , government , parents , and the private sector collaborated to make a world-class future for South Korean children .", 'The City Without Drugs organisation is still active , as is their YouTube channel . It features hundreds of videos of drug addicts being dragged half-conscious through the street , their faces not blurred , or confessing their alleged worthlessness , their hopelessness , their shame .', '" We know we have an affordable housing crisis , both nationally , provincially in the city . This is one part of it , and if we can get this right , it would be a good step for a very vulnerable population . "', "THE jagged rocks , the stony beaches , the sweeping , heather covered hills ... the last views of the old country that faded from sight when a generation of immigrants set sail for the new world ( you can read that in Liam Neeson 's voice if you want ) .", '" In addition , the Members of Parliament will visit two projects that focus on the inclusion of street children and victims of acid attacks to demonstrate their solidarity with those vulnerable groups in need of support . Finally , on April 29 the delegation will brief the journalists on the outcome of the visit at a press conference . "', 'Even though I am now an **33;54;TOOLONG , or if you prefer , an illegal-legal-immigrant , I love this country . It is my home . And I will not stand by and watch an immigration system destroy lives and families . While I still have an ounce of breath in me , it will be to see comprehensive immigration reform in this country -- that a more humane and functional system of immigration be introduced to benefit not only the country as a whole , but all immigrants at every level , of all racial and economic backgrounds .', "John 's first calling was acting . He studied drama at Kinsale College of Education in 2009 and a year later , moved into directing . A few years ago , he staged No Borders , which dealt with the plight of refugees and asylum-seekers .", 'The effect of opening the armouries to the homeless will be to close the armouries to the surrounding community -- taking from one group to give to another . <h> More from the Toronto Star &amp; Partners <h> LOADING', 'Dr. Erin Schryer , executive director of Elementary Literacy , a New Brunswick reading-based program , said the representatives will then distribute the books to children in need .', 'Veterans left on scrapheap : The homeless plight of former servicemen and women', "of the Disappearances Commission in the 1990 's to the findings of the Lessons Learnt and Reconciliation Commission ( 2011 ) to the most recent report of the Consultation Task Force on Reconciliation ( 2017 ) , it has been a long and undeniably hopeless ride for Sri Lanka 's victims . Throughout that process , which has also been littered ... <h> Contemptuously rejecting the path cut by venal politicians", '" I recognized that I \'d made a number of vulnerable people miserable . I was very unhappy with myself . "', 'To fulfill her campaign pledge to offer a pathway to " full and equal citizenship " to millions of immigrants without legal residency , Clinton will need to make compromises with Congress -- and thus with Republicans .']

Their coreference resolution versions: 

- " People do n't understand the hurt , people do n't understand the pain . I 've read about women with women with their children sleeping in cars , sleeping in hotel rooms children sleeping in cars , sleeping in hotel rooms and it 's criminal . If women with their children sleeping in cars , sleeping in hotel rooms 're lucky and women with their children sleeping in cars , sleeping in hotel rooms come across COPE Galway and the ladies in Osterley , then there 's hope . "

- Sheepherding in America has always been an immigrant 's job , too dirty , too cold and too lonely for anyone with options .

- He said : " We need improved security for civilians and aid workers and access to all those in need , but We must also build a bigger humanitarian muscle to provide for the suffering millions .

- myself continued , " myself stepped away from hiding behind a fabricated version of myself . myself no longer put actions behind myself fears and insecurities . myself made a choice to redirect myself energy to be a catalyst for change . To create a channel for themselves to become the truest versions of themselves , along with myself. "

- Haiti has legal protections for the disabled on paper , but legal protections for the disabled on paper are poorly implemented . Disabled Haitians have few opportunities to work and too many youngsters with disabilities languish out of sight at home instead of going to school . Some impoverished parents abandon disabled kids outside state institutions or farm disabled kids out as domestic servants .

# Effect of Ensembles
Compare ensembles for roberta and bert

In [ ]:
# Sentences where ensemble correct, roberta wrong 
cw = df_val[(y_true == y_pred_final) & (y_true != y_pred_roberta_ensemble)]
display(cw[["keyword", "text", "bool_labels"]].sample(frac=1).head()) 
print(cw["bool_labels"].value_counts())

# Sentences where ensemble correct, bert wrong 
cw = df_val[(y_true == y_pred_final) & (y_true != y_pred_bert_ensemble)]
display(cw[["keyword", "text", "bool_labels"]].sample(frac=1).head()) 
print(cw["bool_labels"].value_counts())

# Roberta wrong on mostly false labels, meaning it tends to over-predict for true labels
# On the other hand, BERT tends to under-predict true labels.

,keyword,text,bool_labels
1898,migrant,"( Bloomberg ) -- California Senator Kamala Harris charged that the Trump administration had committed "" crimes against humanity "" after meeting at a U.S. detention center on Friday with immigrant mothers who had been separated from their children .",False
1139,hopeless,""" It beggars belief this scheme has been cobbled together ten weeks from the election when for more than a year Bill English has preferred to write off young unemployed people as pretty damn hopeless and too drugged and lazy .",False
462,in-need,"So starting in 1964 and for almost a decade , the federal government poured at least some of its resources in the direction they should have been going all along : toward those who were most in need . Longstanding programs like Head Start , Legal Services , and the Job Corps were created . Medicaid was established . Poverty among seniors was significantly reduced by improvements in Social Security .",False
135,homeless,"With a mission to "" strive every day to create a safe haven where homeless women and children find stability and access to the basic needs of life "" , the Elfreeda Foundation launched its open shelter on the 11th of August 2017 . In attendance were dignitaries such as : the wife of the vice president of Nigeria , Her Excellency Dolapo Osinbajo ; the governor of Imo State , His Excellency Owelle Anayo Rochas Okorocha ( OON ) ; wife of the governor of Imo State , Nneoma Nkechi Rochas Okorocha ; wife of the governor of Enugu state , Monica Ugwuanyi ; the chief of staff of the Imo State Government , Honorable Uche Nwosu ; publisher of Genevieve Magazine , Betty Irabor amongst others .",True
287,women,"She added : "" I would also like to carefully point out that the issue was not her religious beliefs , but rather it is about choosing to treat men and women differently by shaking the hands of women but not men . """,False

bool_labels
False    12
True      1
Name: count, dtype: int64

,keyword,text,bool_labels
104,vulnerable,The Minister said a society 's measure of its humanity is how it treats its weakest and most vulnerable members .,True
110,refugee,"Bus driver Cathal Carroll asks if I 've heard the news this morning . I have n't . Four thousand souls have just been rescued from the waters of the Mediterranean , he says . All of them African refugees . All fleeing hunger and persecution in their native lands . What do I think about that ?",True
474,women,"I am a Jaffna Tamil residing in the USA and I see the Sri Lankan professionals over here , both the Tamils and Sinhalese , holding top positions in Research , Universities HighTech industries , Law , and Finance.But then looking at the sterile Arab countries all we see are Sri Lankan women working as maids and servents to the rags to riches Arabs.A self respecting society would n't allow its women to be transported as maids to foreign land .",False
1034,poor-families,"Once that is done , the family will work toward raising funds to build small homes for poor families and women in crisis .",False
73,disabled,""" In particular , the programmes to support blind and disabled golf impress me both as an avid golfer and a passionate believer in the "" power of sport "" , to bring people together and transform lives for the better , "" said Mr Key .",True

bool_labels
True     44
False    29
Name: count, dtype: int64